TRUNCATE TABLE ARTISTS_RECSTUDIOS_RELATION;
TRUNCATE TABLE BOOKINGS;
TRUNCATE TABLE EQUIPMENT;
TRUNCATE TABLE ROOMS;
TRUNCATE TABLE ARTISTS;
TRUNCATE TABLE RECORDING_STUDIOS;

-- Artists
INSERT INTO ARTISTS (NAME, MUSIC_GENRE, PROFESSION, BIRTH_DATE, PHONE_ARTIST, EMAIL_ARTIST)
VALUES ('The Weeknd', 'Pop', 'Singer', TO_DATE('1990-02-16', 'YYYY-MM-DD'), 478031245, 'theweeknd@gmail.com');
INSERT INTO ARTISTS (NAME, MUSIC_GENRE, PROFESSION, BIRTH_DATE, PHONE_ARTIST, EMAIL_ARTIST)
VALUES ('Reinier Zonneveld', 'Techno', 'Producer', TO_DATE('1991-01-30', 'YYYY-MM-DD'), 499021456, 'reinier.zonneveld@gmail.com');
INSERT INTO ARTISTS (NAME, MUSIC_GENRE, PROFESSION, BIRTH_DATE, PHONE_ARTIST, EMAIL_ARTIST)
VALUES ('Eli Brown', 'Techno', 'Producer', TO_DATE('1989-09-12', 'YYYY-MM-DD'), 497032848, 'elibrown@gmail.com');
INSERT INTO ARTISTS (NAME, MUSIC_GENRE, PROFESSION, BIRTH_DATE, PHONE_ARTIST, EMAIL_ARTIST)
VALUES ('SG Lewis', 'Pop', 'Singer', TO_DATE('1994-04-09', 'YYYY-MM-DD'), 476149593, 'sglewis@gmail.com');
INSERT INTO ARTISTS (NAME, MUSIC_GENRE, PROFESSION, BIRTH_DATE, PHONE_ARTIST, EMAIL_ARTIST)
VALUES ('Drake', 'Rap', 'Singer', TO_DATE('1986-10-24', 'YYYY-MM-DD'), 499375382, 'contact@drake.com');

-- Recording_Studios
INSERT INTO RECORDING_STUDIOS (STUDIO_NAME, ADDRESS, LOCATION, PHONE_STUDIO, EMAIL_STUDIO, LOCAL_ENGINEER)
VALUES ('Abbey Road', 'Italiëlei 2','ANTWERPEN', 475021343, 'abbeyroad@gmail.com', 1);
INSERT INTO RECORDING_STUDIOS (STUDIO_NAME, ADDRESS, LOCATION, PHONE_STUDIO, EMAIL_STUDIO, LOCAL_ENGINEER)
VALUES ('The Warehouse Studios', 'Merksemsebaan 179','WIJNEGEM', 498931988, 'warehousestudios@outlook.com', 0);
INSERT INTO RECORDING_STUDIOS (STUDIO_NAME, ADDRESS, LOCATION, PHONE_STUDIO, EMAIL_STUDIO, LOCAL_ENGINEER)
VALUES ('Drumcode Studios', 'Koningstraat 14','GENT', 499195183, 'info@drumcode.com', 1);
INSERT INTO RECORDING_STUDIOS (STUDIO_NAME, ADDRESS, LOCATION, PHONE_STUDIO, EMAIL_STUDIO, LOCAL_ENGINEER)
VALUES ('Valhalla Recording Studios', 'Palmstraat 32','HASSELT', 478392935, 'record@valhallastudios.com', 0);
INSERT INTO RECORDING_STUDIOS (STUDIO_NAME, ADDRESS, LOCATION, PHONE_STUDIO, EMAIL_STUDIO, LOCAL_ENGINEER)
VALUES ('Universal Studios', 'Rue Picard 7','BRUSSEL', 27758140, 'contact@universalmusic.be', 1);

-- Rooms
INSERT INTO ROOMS (ROOM_NAME, AREA_INSQM, COSTPERHOUR, SINGER_BOOTH, INSTR_REC_BOOTH, RECORDING_STUDIOS_STUDIO_CODE)
VALUES ('Road Prince', 45.12, 100, 1, 1, (SELECT studio_code FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'ABBEY ROAD'));
INSERT INTO ROOMS (ROOM_NAME, AREA_INSQM, COSTPERHOUR, SINGER_BOOTH, INSTR_REC_BOOTH, RECORDING_STUDIOS_STUDIO_CODE)
VALUES ('Filth On Acid', 34.35, 75, 0, 0, (SELECT studio_code FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'THE WAREHOUSE STUDIOS'));
INSERT INTO ROOMS (ROOM_NAME, AREA_INSQM, COSTPERHOUR, SINGER_BOOTH, INSTR_REC_BOOTH, RECORDING_STUDIOS_STUDIO_CODE)
VALUES ('Beyer', 23.76, 65, 0, 0, (SELECT studio_code FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'DRUMCODE STUDIOS'));
INSERT INTO ROOMS (ROOM_NAME, AREA_INSQM, COSTPERHOUR, SINGER_BOOTH, INSTR_REC_BOOTH, RECORDING_STUDIOS_STUDIO_CODE)
VALUES ('Atlantis', 92.52, 135, 1, 1, (SELECT studio_code FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'VALHALLA RECORDING STUDIOS'));
INSERT INTO ROOMS (ROOM_NAME, AREA_INSQM, COSTPERHOUR, SINGER_BOOTH, INSTR_REC_BOOTH, RECORDING_STUDIOS_STUDIO_CODE)
VALUES ('Michael',103.59, 185, 1, 1, (SELECT studio_code FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'UNIVERSAL STUDIOS'));


-- Equipment
INSERT INTO EQUIPMENT (MIXING_CONSOLE, MONITORS, HARDWARE, DAW, SOFTWARE, SYNTHS, VOCAL_MIC, ROOMS_ROOM_CODE, RO_REC_STU_CODE)
VALUES ('SSL', 'Dynaudio', 'LA-2A compressor, 1176 compressor, Pultec', 'ProTools', 'Melodyne, Fabfilter Bundle, iZotope Bundle', 'Moog, Roland, Nord Lead', 'Neumann', (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'ROAD PRINCE'),(SELECT RECORDING_STUDIOS_STUDIO_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'ROAD PRINCE'));
INSERT INTO EQUIPMENT (MIXING_CONSOLE, MONITORS, HARDWARE, DAW, SOFTWARE, SYNTHS, VOCAL_MIC, ROOMS_ROOM_CODE, RO_REC_STU_CODE)
VALUES ('NEVE', 'Barefoot', 'Distressor, Universal Audio', 'Ableton', 'UAD Bundle, Fabfilter Bundle, Waves Bundle', 'Moog, Roland', 'Shure', (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'FILTH ON ACID'),(SELECT RECORDING_STUDIOS_STUDIO_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'FILTH ON ACID'));
INSERT INTO EQUIPMENT (MIXING_CONSOLE, MONITORS, HARDWARE, DAW, SOFTWARE, SYNTHS, ROOMS_ROOM_CODE, RO_REC_STU_CODE)
VALUES ('AVID', 'Adam', 'Distressor, Fairchild compressors, Pultec', 'Ableton', 'iZotope Bundle, Waves Bundle, Fabfilter Bundle', 'Roland, Prophet', (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'BEYER'),(SELECT RECORDING_STUDIOS_STUDIO_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'BEYER'));
INSERT INTO EQUIPMENT (MIXING_CONSOLE, MONITORS, HARDWARE, DAW, SOFTWARE, SYNTHS, VOCAL_MIC, ROOMS_ROOM_CODE, RO_REC_STU_CODE)
VALUES ('API', 'Focal', 'LA-2A compressor, 1176 compressor, Fairchild comp', 'Logic', 'Melodyne, Waves Bundle, iZotope Bundle', 'Nord Lead, Prophet, Oberheimer, Moog, Roland','Sony',(SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'ATLANTIS'),(SELECT RECORDING_STUDIOS_STUDIO_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'ATLANTIS'));
INSERT INTO EQUIPMENT (MIXING_CONSOLE, MONITORS, HARDWARE, DAW, SOFTWARE, SYNTHS, VOCAL_MIC, ROOMS_ROOM_CODE, RO_REC_STU_CODE)
VALUES ('SSL', 'Genelec', 'LA-2A compressor, Universal Audio, 1176 compressor', 'ProTools', 'Melodyne, UAD Bundle, iZotope Bundle', 'Nord Lead, Yamaha, Prophet, Moog', 'Neumann', (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'MICHAEL'),(SELECT RECORDING_STUDIOS_STUDIO_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'MICHAEL'));

-- Bookings
INSERT INTO BOOKINGS(RES_DATE, START_HOUR, END_HOUR, ARTISTS_ARTIST_ID, ROOMS_ROOM_CODE, ROOMS_STUDIO_CODE)
VALUES (TO_DATE('2023-03-15', 'YYYY-MM-DD'), TO_DATE('10:00','HH24:MI'), TO_DATE('12:00','HH24:MI'), (SELECT ARTIST_ID FROM ARTISTS WHERE UPPER(NAME) = 'THE WEEKND'), (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'ROAD PRINCE'), (SELECT STUDIO_CODE FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'ABBEY ROAD'));
INSERT INTO BOOKINGS(RES_DATE, START_HOUR, END_HOUR, ARTISTS_ARTIST_ID, ROOMS_ROOM_CODE, ROOMS_STUDIO_CODE)
VALUES (TO_DATE('2023-04-06', 'YYYY-MM-DD'), TO_DATE('13:00','HH24:MI'), TO_DATE('17:00','HH24:MI'), (SELECT ARTIST_ID FROM ARTISTS WHERE UPPER(NAME) = 'REINIER ZONNEVELD'), (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'FILTH ON ACID'), (SELECT STUDIO_CODE FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'THE WAREHOUSE STUDIOS'));
INSERT INTO BOOKINGS(RES_DATE, START_HOUR, END_HOUR, ARTISTS_ARTIST_ID, ROOMS_ROOM_CODE, ROOMS_STUDIO_CODE)
VALUES (TO_DATE('2023-04-13', 'YYYY-MM-DD'), TO_DATE('09:00','HH24:MI'), TO_DATE('12:00','HH24:MI'), (SELECT ARTIST_ID FROM ARTISTS WHERE UPPER(NAME) = 'ELI BROWN'), (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'BEYER'), (SELECT STUDIO_CODE FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'DRUMCODE STUDIOS'));
INSERT INTO BOOKINGS(RES_DATE, START_HOUR, END_HOUR, ARTISTS_ARTIST_ID, ROOMS_ROOM_CODE, ROOMS_STUDIO_CODE)
VALUES (TO_DATE('2023-03-28', 'YYYY-MM-DD'), TO_DATE('14:00','HH24:MI'), TO_DATE('16:00','HH24:MI'), (SELECT ARTIST_ID FROM ARTISTS WHERE UPPER(NAME) = 'SG LEWIS'), (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'ATLANTIS'), (SELECT STUDIO_CODE FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'VALHALLA RECORDING STUDIOS'));
INSERT INTO BOOKINGS(RES_DATE, START_HOUR, END_HOUR, ARTISTS_ARTIST_ID, ROOMS_ROOM_CODE, ROOMS_STUDIO_CODE)
VALUES (TO_DATE('2023-05-02', 'YYYY-MM-DD'), TO_DATE('15:00','HH24:MI'), TO_DATE('18:00','HH24:MI'), (SELECT ARTIST_ID FROM ARTISTS WHERE UPPER(NAME) = 'DRAKE'), (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'MICHAEL'), (SELECT STUDIO_CODE FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'UNIVERSAL STUDIOS'));