
-- table count
SELECT 'artists' AS table_name, (SELECT COUNT(*) FROM ARTISTS) AS table_count FROM dual UNION
SELECT 'recording_studios', (SELECT COUNT(*) FROM RECORDING_STUDIOS) FROM dual UNION
SELECT 'rooms', (SELECT COUNT(*) FROM ROOMS) FROM dual UNION
SELECT 'equipment', (SELECT COUNT(*) FROM EQUIPMENT) FROM dual UNION
SELECT 'bookings', (SELECT COUNT(*) FROM BOOKINGS) FROM dual;


-- veel op veel relatie
SELECT name,MUSIC_GENRE, PROFESSION, BIRTH_DATE, PHONE_ARTIST, EMAIL_ARTIST, STUDIO_NAME, ADDRESS, LOCATION, PHONE_STUDIO, EMAIL_STUDIO,LOCAL_ENGINEER
FROM ARTISTS a
         JOIN ARTISTS_RECSTUDIOS_RELATION ar ON ar.A_ARTIST_ID = a.ARTIST_ID
         JOIN RECORDING_STUDIOS r ON r.STUDIO_CODE = ar.RS_STUDIO_CODE;

-- 2 niveau's diep
SELECT STUDIO_NAME, ADDRESS, LOCATION, PHONE_STUDIO, EMAIL_STUDIO, LOCAL_ENGINEER, ROOM_NAME, AREA_INSQM, COSTPERHOUR, SINGER_BOOTH, INSTR_REC_BOOTH, MIXING_CONSOLE, MONITORS, HARDWARE, DAW, SOFTWARE, SYNTHS, VOCAL_MIC
FROM RECORDING_STUDIOS r
    JOIN ROOMS ro ON ro.RECORDING_STUDIOS_STUDIO_CODE = r.STUDIO_CODE
    JOIN EQUIPMENT e ON e.ROOMS_ROOM_CODE = ro.ROOM_CODE
ORDER BY STUDIO_NAME, ROOM_NAME, EQUIPMENT_CODE;

-- niet eerder getoonde tabellen
SELECT RES_DATE, START_HOUR, END_HOUR, NAME, MUSIC_GENRE, PROFESSION, BIRTH_DATE, PHONE_ARTIST, EMAIL_ARTIST, STUDIO_NAME, ADDRESS, LOCATION, PHONE_STUDIO, EMAIL_STUDIO, LOCAL_ENGINEER, ROOM_NAME, AREA_INSQM, COSTPERHOUR, SINGER_BOOTH, INSTR_REC_BOOTH,MIXING_CONSOLE,MONITORS, HARDWARE, DAW, SOFTWARE, SYNTHS,  VOCAL_MIC
FROM BOOKINGS b
    JOIN ARTISTS a ON a.ARTIST_ID = b.ARTISTS_ARTIST_ID
    JOIN RECORDING_STUDIOS r ON r.STUDIO_CODE = b.ROOMS_STUDIO_CODE
    JOIN ROOMS ro ON b.ROOMS_ROOM_CODE = ro.ROOM_CODE
    JOIN EQUIPMENT e ON e.ROOMS_ROOM_CODE = b.ROOMS_ROOM_CODE AND e.RO_REC_STU_CODE = b.ROOMS_STUDIO_CODE
ORDER BY RES_DATE, NAME, STUDIO_NAME, ROOM_NAME;



-- Constraints M2

--- Bookings: end hour > start hour
INSERT INTO BOOKINGS (START_HOUR, END_HOUR, ARTISTS_ARTIST_ID, ROOMS_ROOM_CODE, ROOMS_STUDIO_CODE)
VALUES (TO_TIMESTAMP('17:00','HH24:MI'), TO_TIMESTAMP('15:00','HH24:MI'), (SELECT ARTIST_ID FROM ARTISTS WHERE UPPER(NAME) = 'REINIER ZONNEVELD'), (SELECT ROOM_CODE FROM ROOMS WHERE UPPER(ROOM_NAME) = 'FILTH ON ACID'), (SELECT STUDIO_CODE FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'THE WAREHOUSE STUDIOS'));


-- Artists: music genre - minimum 3 characters
INSERT INTO ARTISTS(MUSIC_GENRE) VALUES ('ra');


-- Artists: email_artist - must contain @
INSERT INTO ARTISTS(EMAIL_ARTIST) VALUES ('matthias.vermeiren&gmail.com');


-- Recording_Studios: email_studio - must contain @
INSERT INTO RECORDING_STUDIOS (EMAIL_STUDIO) VALUES ('recording.studio#gmail.com');


-- Recording_Studios: location - uppercase
INSERT INTO RECORDING_STUDIOS (LOCATION) VALUES('antwerpen');


-- Rooms: area_insqm - max 500
INSERT INTO ROOMS (AREA_INSQM, RECORDING_STUDIOS_STUDIO_CODE) VALUES (750, (SELECT studio_code FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'ABBEY ROAD'));


-- Rooms: costperhour - max 200
INSERT INTO ROOMS (COSTPERHOUR, RECORDING_STUDIOS_STUDIO_CODE) VALUES (350, (SELECT studio_code FROM RECORDING_STUDIOS WHERE UPPER(STUDIO_NAME) = 'ABBEY ROAD'));
